-- MySQL Script generated by MySQL Workbench
-- Mon Jun 21 13:13:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema makeup_mirror
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema makeup_mirror
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `makeup_mirror` DEFAULT CHARACTER SET utf8 ;
USE `makeup_mirror` ;

-- -----------------------------------------------------
-- Table `makeup_mirror`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeup_mirror`.`user` (
                                                      `user_id` BIGINT UNSIGNED NOT NULL,
                                                      `user_name` VARCHAR(30) NOT NULL,
    `user_encryptedData` VARCHAR(1024) NOT NULL,
    `current_mirror_id` BIGINT UNSIGNED NULL,
    `gender` TINYINT UNSIGNED NULL,
    `IV` VARCHAR(64) NOT NULL,
    PRIMARY KEY (`user_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makeup_mirror`.`mirror`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeup_mirror`.`mirror` (
                                                        `mirror_id` BIGINT UNSIGNED NOT NULL,
                                                        `current_user_id` BIGINT UNSIGNED NULL,
                                                        `serial_number` INT UNSIGNED NULL,
                                                        `mirror_type` INT UNSIGNED NULL,
                                                        PRIMARY KEY (`mirror_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `makeup_mirror`.`user_mirror_relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `makeup_mirror`.`user_mirror_relationship` (
                                                                          `connection_id` BIGINT UNSIGNED NOT NULL,
                                                                          `user_id` BIGINT UNSIGNED NOT NULL,
                                                                          `mirror_id` BIGINT UNSIGNED NOT NULL,
                                                                          PRIMARY KEY (`connection_id`),
    INDEX `user_id_idx` (`user_id` ASC),
    INDEX `mirror_id_idx` (`mirror_id` ASC),
    CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `makeup_mirror`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `mirror_id`
    FOREIGN KEY (`mirror_id`)
    REFERENCES `makeup_mirror`.`mirror` (`mirror_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
